config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

    # get 'patient_address', to: 'patients#new_patient_address'
    # get 'patient_address', to: 'patients#create_patient_address'

  root to: "karutes#index"
  # resources :restaurants
  #   namespace :admin do
  resources :restaurants, only: [:show] 

  resources :patients, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :patient_addresses, shallow: true
    resources :karutes, shallow: true
    collection do
      get 'search'
    end
  end

  resources :menus, only: [:index]
  resources :bulogs, only: [:index]
  resources :accesses, only: [:index]
  resources :shops, only: [:index]
  resources :infomations, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  with_options presence: true do
    validates :postal_code, format: { with: /\A\d{3}-\d{4}\z/ }
    validates :prefecture
    validates :city
    validates :address
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/karute.rb
class Karute < ApplicationRecord
  belongs_to :patient, optional: true
  validates :patient_id,{presence: true}
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_one :karute, dependent: :destroy
  has_one :patient_address, dependent: :destroy

  with_options presence: true do
    validates :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birth_date_id
    validates :phone_number, format: { with: /\A\d{11}\z/ }
  end

  def self.search(search)
    if search != ""
      Patient.where('family_name LIKE ? OR first_name LIKE ? OR family_name_kana LIKE ? OR first_name_kana LIKE ? OR phone_number LIKE ? ' , "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Patient.all
    end
  end
end

app/models/patient_address.rb
class PatientAddress < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  
  belongs_to :patient, optional: true

  with_options presence: true do
    validates :postal_code, format: { with: /\A\d{3}-\d{4}\z/ }
    validates :prefecture_id
    validates :city
    validates :address
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '愛媛県' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' },
    { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' },
    { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' },
    { id: 47, name: '沖縄県' },
  ]

  include ActiveHash::Associations
  has_many :patient_addresses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}+\z/i }
    validates :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birth_date_id
    validates :phone_number, format: { with: /\A\d{11}\z/ }
  end
  has_one :address
  # has_one :karute
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  def index
  end
end

app/controllers/bulogs_controller.rb
class BulogsController < ApplicationController
  def index
  end
end

app/controllers/karutes_controller.rb
class KarutesController < ApplicationController
  before_action :if_not_admin, except: [:index]
  
  def index
    @patients = Patient.order :family_name_kana, :first_name_kana
    # where.not(id: current_user.id) 
    # .all
  end

  def new
    @karute = Karute.new

  end

  def create
    @karute = Karute.new(karute_params)
    @karute.patient_id = params[:patient_id]
    if @karute.save
      redirect_to patient_path(@karute.patient_id)
    else
      render :new
    end
  end

  def edit
    @karute = Karute.find(params[:id])
    @karute.patient_id = params[:patient_id]
  end

  def update
    @karute = Karute.find(params[:id])
    if @karute.update(karute_params)
      redirect_to patient_path(@karute.patient_id)
    else
      render :edit
    end
  end
      
  private

  def karute_params
    params.require(:karute).permit(:pain, :illness, :history, :medicine, :habit, :memo, :date)
  end

  def if_not_admin
    redirect_to root_path unless current_user && current_user.admin?
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :if_not_admin

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patient_path(@patient.id)
    else
      render :new
    end
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update(patient_params)
      redirect_to patient_path
    else
      render :edit
    end
  end

  def search
    @patients = Patient.search(params[:keyword])
  end

  def destroy
    @patient = Patient.find(params[:id])
    if @patient.destroy
      redirect_to root_path
    else
      render :show
    end
  end


  private

  def patient_params
    params.require(:patient).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :birth_date_id, :phone_number)
  end

  def if_not_admin
    redirect_to root_path unless current_user && current_user.admin?
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
  end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulogs_helper.rb
module BulogsHelper
end

app/helpers/infomations_helper.rb
module InfomationsHelper
end

app/helpers/karutes_helper.rb
module KarutesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/patient_addresses_helper.rb
module PatientAddressesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/karutes/_fotter.html.erb
<div class='top-page-fotter'>
  <h2 class="fotter_title">
    <i class="far fa-lightbulb"></i>
    <span>
      <p>ボディーバランスケア Amollir -あもりーる-</p>
      <p>営業時間</p>
      <p>午前９時～午後７時（最終受付）</p>
      <p>年末年始休業</p>
      <p>毎週土曜日は宇和店のため松山店休業</p>
    </span>
  </h2>
  <div class="admin_b">
    <%= link_to '（仮）管理者', new_user_session_path, class: "admin-list" %>
  </div> 

  
</div>

app/views/karutes/_header.html.erb
<%# CSS・・・assets/stylesheets/karute/header.css %>
<header class='top-page-header'>
  <div class='left-header'>
    <%= link_to image_tag("0.png", class:"amollir_logo"), "/" %> 
  </div>
  <div class='right-header'> 
    <div class=right-top>
      <div class="admin-s">
          <%= link_to '@管理者', new_user_session_path, class: "admin-list" %>
      </div>
    </div>
    <div class="rignt-bottom">
      <ul class='header_list'>
        <li class='menu_list'><%= link_to 'メニュー', menus_path, class: "course-list" %></li>
        <li class='menu_list'><%= link_to '店の様子', shops_path, class: "shop-list" %></li>
        <li class='menu_list'><%= link_to 'アクセス/予約', accesses_path, class: "access-list" %></li>
        <li class='menu_list'><%= link_to 'ブログ', bulogs_path, class: "blog-list" %></li>
        <li class='menu_list'><%= link_to 'トピック', infomations_path, class: "inquiry-list" %></li>
        <%# <li class='menu_list'><%= link_to '（仮）管理者', new_user_session_path, class: "admin-list" %>
        <%# <li ><%= link_to '（仮）管理者', rails_admin_path, class: "admin-list" %></li>
      </ul>
    </div>    
  </div>
</header>
<h1>
</h1>

app/views/karutes/edit.html.erb
<div class="new_edit">  

  <h2 class="new_edit_title">カルテ編集</h2>

  <%= form_with model: @karute, local: true do |f| %> 
  <%= render 'shared/error_messages', model: f.object %> 

    

      <div class="field">
        <%= f.label "作成日" %><br />
        <%= f.text_field :date %>
      </div>

      <div class="field">
        <%= f.label "痛みのある部位" %><br />
        <%= f.text_field :pain %>
      </div>

      <div class="field">
        <%= f.label "既往症" %><br />
        <%= f.text_field :illness %>
      </div>

      <div class="field">
        <%= f.label "通院歴" %><br />
        <%= f.text_field :history %>
      </div>

      <div class="field">
        <%= f.label "服用薬" %><br />
        <%= f.text_field :medicine %>
      </div>

      <div class="field">
        <%= f.label "日常的に行っている行動" %><br />
        <%= f.text_field :habit %>
      </div>

      <div class="field">
        <%= f.label "メモ" %><br />
        <%= f.text_field :memo %>
      </div>

      <div class="actions">
        <%= f.submit "カルテ作成", class: :form__btn  %>
        <p><%=link_to 'もどる', root_path, class:"back-btn" %></p>
      </div>

  <% end %>
</div>  

app/views/karutes/index.html.erb
<%= render "header"%>

<div class="admin">

  <% if user_signed_in?%>
    <% if current_user.admin? %>
      <div class="tab">
        <h2 class="iti">一覧は管理者のみ表示されます</h2>
        
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "log_out_btn" %>
        <%= link_to '患者登録', new_patient_path, class: "admin_btn" %>
        <div class="search">
          <%= form_with(url: search_patients_path, local: true, method: :get, class: "search-form") do |form| %>
            <%= form.text_field :keyword, placeholder: "名前、電話番号から検索", class: "search-input" %>
            <%= form.submit "検索", class: "search-btn" %>
          <% end %>
        </div>  

      </div>  

      <div class="karute_user">
        <h2 class=k_title>患者カルテ一覧</h2>
        <ul class='user_list'>
          <% @patients.each do |patient| %>
            <li class='u_list'>
                <%= link_to patient_path(patient.id), method: :get do %> 
                <span class="user_li"><%= patient.family_name %>
                <%= patient.first_name %></span>
                <% end %>
            </li>
          <% end %>
        </ul>
      </div> 
    <% else %> 
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "log_out_btn" %>
    <% end %>
  <% else %>  
    <div class="image1-1">
      <div class="image1">
        <%= image_tag("image_top.png", class:"amollir_top_image") %> 
        <div class="image1_comment">
          <h2>一人一人に合ったオールハンド施術</h2>
          <h2>身体に溜まった老廃物を流し出す</h2>
        </div>  
      </div>
    </div> 
    <div class="top_message">   
      <h1></h1>
        <p class="amollir_comment_top">Amollir       "あもりーる"</p>
        <p class="amollir_comment">フランス語で、「和らぐ」という意味の他に「柔らかくなる、癒し」などの意味もあります。</p>
        <p class="amollir_comment">あなたの身体の痛みと心の疲れを和らげる癒やしのサロンでありたいと思っています。</p>
        <p class="amollir_comment">身体のお悩みに合わせたきめ細かい施術と、心のこもったサービスを提供させて頂けるよう、日々目指しております。</p>
      <h1></h1>
    </div>   
    <div class="image1-2">
      <%= image_tag("image_top2.png", class:"amollir_top_image2-1") %> 
      <div class="image2_coment">
        <%= image_tag("image_top_waku.png", class:"amollir_top_image2-2") %> 
      </div>
    </div>

    <div class="s_nagare">
      <h2 class="s_nagare_t">施術の流れ</h2>

      <div class="n_1_con">
        <div class="n_image">
          <%= image_tag("image_caunseling.png", class:"amollir_top_image2-1") %> 
        </div>
        <div class="n_comment">
          <p class="n_1">カウンセリング</p>
          <p>カウンセリングをして、お一人お一人の体の状態に合わせて施術をおこないます</p>
          <p>体のお悩みをお気軽にご相談ください</p>
          <p>元水泳インストラクターの経験から、様々な運動療法もアドバイスしています</p>
        </div>
      </div>

      <div class="n_1_con">
        <div class="n_image">
          <%= image_tag("image_sezyutu.png", class:"amollir_top_image2-1") %> 
        </div>
        <div class="n_comment">
          <p class="n_1">施術</p>
          <p>マンツーマンでの施術ですので時間を忘れてリラックスして頂けます</p>
          <p>バキバキしない安心の施術です</p>
          <p>当店ではお一人のお客様に対して、一人の施術者が担当しております</p>
          <p>入れ替わり立ち替わりお客様が出入りするシステムではないので、その都度換気や除菌など徹底した衛生管理の元、お客様をお迎えしております</p>
        </div>
      </div>

      <div class="n_1_con">
        <div class="n_image">
          <%= image_tag("image_sezyutu_after.png", class:"amollir_top_image2-1") %> 
        </div>
        <div class="n_comment">
          <p class="n_1">施術後</p>
          <p>お飲み物をご用意しております</p>
          <p>コーヒー・紅茶・ハーブティー(5種類)の中からお好きな物をお選び下さい</p>
          <p>水分を補って、更にめぐりの良い体へ…</p>
        </div>
      </div>
    </div>


    <div class='top-page-fotter'>
      <h2 class="fotter_title">
        <i class="far fa-lightbulb"></i>
        <span>
          <p class="shop_name_hutter">ボディーバランスケア Amollir -あもりーる-</p>
          <p class="shop_time">営業時間</p>
          <p class="shop_time">午前９時～午後７時（最終受付）</p>
          <p class="shop_time">年末年始休業</p>
          <p class="shop_time">毎週土曜日は宇和店のため松山店休業</p>
        </span> 
      </h2>
    </div>  

    <div class="tell">
      <h3 title="tell_coment">ご予約<p class="tell_number">089-904-7180</p><p>※非通知は繋がりません</p></h3>
    </div> 
    
     
  <% end %>

  

</div>

app/views/karutes/new.html.erb
<div class="new_edit">  
  <h2 class="new_edit_title">カルテ入力</h2>

  <%= form_with model: @karute, url: patient_karutes_path, local: true do |f| %> 
  <%= render 'shared/error_messages', model: f.object %> 

    <div class="field">
      <%= f.label "作成日" %><br />
      <%= f.text_field :date %>
    </div>

    <div class="field">
      <%= f.label "痛みのある部位" %><br />
      <%= f.text_field :pain %>
    </div>

    <div class="field">
      <%= f.label "既往症" %><br />
      <%= f.text_field :illness %>
    </div>

    <div class="field">
      <%= f.label "通院歴" %><br />
      <%= f.text_field :history %>
    </div>

    <div class="field">
      <%= f.label "服用薬" %><br />
      <%= f.text_field :medicine %>
    </div>

    <div class="field">
      <%= f.label "日常的に行っている行動" %><br />
      <%= f.text_field :habit %>
    </div>

    <div class="field">
      <%= f.label "メモ" %><br />
      <%= f.text_field :memo %>
    </div>

    <div class="actions">
      <%= f.submit "カルテ作成", class: :form__btn  %>
      <p><%=link_to 'もどる', root_path, class:"back-btn" %></p>
    </div>

  <% end %>

</div>