config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

    # get 'patient_address', to: 'patients#new_patient_address'
    # get 'patient_address', to: 'patients#create_patient_address'

  root to: "karutes#index"
  # resources :restaurants
  #   namespace :admin do
  resources :restaurants, only: [:show] 

  resources :patients, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :patient_addresses, shallow: true
    resources :karutes, shallow: true
    collection do
      get 'search'
    end
  end

  resources :menus, only: [:index]
  resources :bulogs, only: [:index]
  resources :accesses, only: [:index]
  resources :shops, only: [:index]
  resources :infomations, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  with_options presence: true do
    validates :postal_code, format: { with: /\A\d{3}-\d{4}\z/ }
    validates :prefecture
    validates :city
    validates :address
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/karute.rb
class Karute < ApplicationRecord
  belongs_to :patient, optional: true
  validates :patient_id,{presence: true}
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_one :karute, dependent: :destroy
  has_one :patient_address, dependent: :destroy

  with_options presence: true do
    validates :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birth_date_id
    validates :phone_number, format: { with: /\A\d{11}\z/ }
  end

  def self.search(search)
    if search != ""
      Patient.where('family_name LIKE ? OR first_name LIKE ? OR family_name_kana LIKE ? OR first_name_kana LIKE ? OR phone_number LIKE ? ' , "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Patient.all
    end
  end
end

app/models/patient_address.rb
class PatientAddress < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  
  belongs_to :patient, optional: true

  with_options presence: true do
    validates :postal_code, format: { with: /\A\d{3}-\d{4}\z/ }
    validates :prefecture_id
    validates :city
    validates :address
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '愛媛県' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' },
    { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' },
    { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' },
    { id: 47, name: '沖縄県' },
  ]

  include ActiveHash::Associations
  has_many :patient_addresses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}+\z/i }
    validates :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birth_date_id
    validates :phone_number, format: { with: /\A\d{11}\z/ }
  end
  has_one :address
  # has_one :karute
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :if_not_admin, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  private
  def if_not_admin
    redirect_to root_path unless @current_user.admin?
  end

end

app/controllers/bulogs_controller.rb
class BulogsController < ApplicationController
  def index
  end
end

app/controllers/karutes_controller.rb
class KarutesController < ApplicationController
  before_action :if_not_admin, except: [:index]
  
  def index
    @patients = Patient.order :family_name_kana, :first_name_kana
    # where.not(id: current_user.id) 
    # .all
  end

  def new
    @karute = Karute.new

  end

  def create
    @karute = Karute.new(karute_params)
    @karute.patient_id = params[:patient_id]
    if @karute.save
      redirect_to patient_path(@karute.patient_id)
    else
      render :new
    end
  end

  def edit
    @karute = Karute.find(params[:id])
    @karute.patient_id = params[:patient_id]
  end

  def update
    @karute = Karute.find(params[:id])
    if @karute.update(karute_params)
      redirect_to patient_path(@karute.patient_id)
    else
      render :edit
    end
  end
      
  private

  def karute_params
    params.require(:karute).permit(:pain, :illness, :history, :medicine, :habit, :memo, :date)
  end

  def if_not_admin
    redirect_to root_path unless current_user && current_user.admin?
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
  end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulogs_helper.rb
module BulogsHelper
end

app/helpers/infomations_helper.rb
module InfomationsHelper
end

app/helpers/karutes_helper.rb
module KarutesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/admin/restaurants/show.html.erb
<div class="user_karute_body">
  <div class="top_back_btn">
    <%= link_to '一覧に戻る', root_path %>
  </div>  
  <% unless @user.karute.present?%> 
    <div class="new_karute_btn">
      <p>カルテがありません</p>
      <%= link_to 'カルテを追加', new_user_karute_path(@user.id), method: :get %>
    </div>
  <% else %> 
    <div class="edit_karute_btn">
      <%= link_to 'カルテを編集', edit_karute_path(@user.karute.id), method: :get %>
    </div>  
    <h2 class="page-heading"><%= "#{@user.family_name}#{@user.first_name}さんのカルテ"%></h2>

    <div class="date">
      <p>＜更新日＞</p>
      <%= @user.karute.date %>
    </div>
    <div class="name">
      <p>＜氏名＞</p>
      <div class="kana">
        <%= "#{@user.family_name_kana}#{@user.first_name_kana}" %>
      </div>
      <div class="kanji">
        <%= "#{@user.family_name}#{@user.first_name}" %>
      </div>  
    </div>

    <div class="birth">
      <p>＜誕生日＞</p>
      <%= "#{@user.birth_date_id}生" %>
    </div>

    <div class="address_space">
      <p>＜住所＞</p>
      <div class="postal_code">
        <%= "〒#{@user.address.postal_code}" %>
      </div>

      <div class="address">
        <%= @user.address.prefecture %>
        <%= @user.address.city %>
        <%= @user.address.address %>
        <%= @user.address.building_name %>
      </div>
    </div>
    
    <div class="phone_number">
      <p>＜電話番号＞</p>
      <%= @user.phone_number %>
    </div>

    

    <div class="user_karute">
        <div class="pain">
          <div class="item">
          ＜痛みのある部位＞
          </div>
          <%= @user.karute.pain %>
        </div>
        <div class="illness">
          <div class="item">
          ＜既往症＞
          </div>
          <%= @user.karute.illness %>
        </div>

        <div class="history">
          <div class="item">
          ＜通院歴＞
          </div>
          <%= @user.karute.history %>
        </div>

        <div class="medicine">
          <div class="item">
          ＜服用している薬＞
          </div>
          <%= @user.karute.medicine %>
        </div>

        <div class="habit">
          <div class="item">
          ＜日常的に行っている行動＞
          </div>
          <%= @user.karute.habit %>
        </div>
        <div class="memo">
          <div class="item">
          ＜メモ＞
          </div>
          <%= @user.karute.memo %>
        </div>
    </div>
  <% end %>
</div>  